table Mesures
	lineageTag: 272dc5e8-40da-47c5-8cca-f88374d5e274

	measure ShowFilter = ```
			
			VAR MaxFilters = 3
			RETURN
			IF ( 
			    ISFILTERED ( Calendrier[Annee] ), 
			    VAR ___f = FILTERS ( Calendrier[Annee] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Annee] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Annee], ", " )
			    VAR ___x = "Calendrier[Annee] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Annee mois] ), 
			    VAR ___f = FILTERS ( Calendrier[Annee mois] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Annee mois] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Annee mois], ", " )
			    VAR ___x = "Calendrier[Annee mois] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Date] ), 
			    VAR ___f = FILTERS ( Calendrier[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Date] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Date], ", " )
			    VAR ___x = "Calendrier[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Jour ouvre] ), 
			    VAR ___f = FILTERS ( Calendrier[Jour ouvre] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Jour ouvre] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Jour ouvre], ", " )
			    VAR ___x = "Calendrier[Jour ouvre] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Nom du jour] ), 
			    VAR ___f = FILTERS ( Calendrier[Nom du jour] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Nom du jour] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Nom du jour], ", " )
			    VAR ___x = "Calendrier[Nom du jour] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Nom du mois] ), 
			    VAR ___f = FILTERS ( Calendrier[Nom du mois] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Nom du mois] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Nom du mois], ", " )
			    VAR ___x = "Calendrier[Nom du mois] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Numero de la semaine] ), 
			    VAR ___f = FILTERS ( Calendrier[Numero de la semaine] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Numero de la semaine] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Numero de la semaine], ", " )
			    VAR ___x = "Calendrier[Numero de la semaine] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Numero du jour] ), 
			    VAR ___f = FILTERS ( Calendrier[Numero du jour] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Numero du jour] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Numero du jour], ", " )
			    VAR ___x = "Calendrier[Numero du jour] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Numero du mois] ), 
			    VAR ___f = FILTERS ( Calendrier[Numero du mois] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Numero du mois] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Numero du mois], ", " )
			    VAR ___x = "Calendrier[Numero du mois] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Semaine] ), 
			    VAR ___f = FILTERS ( Calendrier[Semaine] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Semaine] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Semaine], ", " )
			    VAR ___x = "Calendrier[Semaine] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Calendrier[Trimestre] ), 
			    VAR ___f = FILTERS ( Calendrier[Trimestre] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Calendrier[Trimestre] )
			    VAR ___d = CONCATENATEX ( ___t, Calendrier[Trimestre], ", " )
			    VAR ___x = "Calendrier[Trimestre] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[annee_debut] ), 
			    VAR ___f = FILTERS ( Chantiers[annee_debut] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[annee_debut] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[annee_debut], ", " )
			    VAR ___x = "Chantiers[annee_debut] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[ca_facture_ht] ), 
			    VAR ___f = FILTERS ( Chantiers[ca_facture_ht] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[ca_facture_ht] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[ca_facture_ht], ", " )
			    VAR ___x = "Chantiers[ca_facture_ht] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[ca_prevu_ht] ), 
			    VAR ___f = FILTERS ( Chantiers[ca_prevu_ht] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[ca_prevu_ht] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[ca_prevu_ht], ", " )
			    VAR ___x = "Chantiers[ca_prevu_ht] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[chantier_id] ), 
			    VAR ___f = FILTERS ( Chantiers[chantier_id] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[chantier_id] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[chantier_id], ", " )
			    VAR ___x = "Chantiers[chantier_id] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[client] ), 
			    VAR ___f = FILTERS ( Chantiers[client] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[client] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[client], ", " )
			    VAR ___x = "Chantiers[client] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[code_postal] ), 
			    VAR ___f = FILTERS ( Chantiers[code_postal] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[code_postal] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[code_postal], ", " )
			    VAR ___x = "Chantiers[code_postal] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[date_debut] ), 
			    VAR ___f = FILTERS ( Chantiers[date_debut] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[date_debut] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[date_debut], ", " )
			    VAR ___x = "Chantiers[date_debut] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[date_fin_prevue] ), 
			    VAR ___f = FILTERS ( Chantiers[date_fin_prevue] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[date_fin_prevue] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[date_fin_prevue], ", " )
			    VAR ___x = "Chantiers[date_fin_prevue] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[date_fin_reelle] ), 
			    VAR ___f = FILTERS ( Chantiers[date_fin_reelle] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[date_fin_reelle] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[date_fin_reelle], ", " )
			    VAR ___x = "Chantiers[date_fin_reelle] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[nom_chantier] ), 
			    VAR ___f = FILTERS ( Chantiers[nom_chantier] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[nom_chantier] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[nom_chantier], ", " )
			    VAR ___x = "Chantiers[nom_chantier] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[type_client] ), 
			    VAR ___f = FILTERS ( Chantiers[type_client] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[type_client] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[type_client], ", " )
			    VAR ___x = "Chantiers[type_client] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[type_travaux] ), 
			    VAR ___f = FILTERS ( Chantiers[type_travaux] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[type_travaux] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[type_travaux], ", " )
			    VAR ___x = "Chantiers[type_travaux] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Chantiers[ville] ), 
			    VAR ___f = FILTERS ( Chantiers[ville] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Chantiers[ville] )
			    VAR ___d = CONCATENATEX ( ___t, Chantiers[ville], ", " )
			    VAR ___x = "Chantiers[ville] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[annee_chantier] ), 
			    VAR ___f = FILTERS ( Couts[annee_chantier] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[annee_chantier] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[annee_chantier], ", " )
			    VAR ___x = "Couts[annee_chantier] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[chantier_id] ), 
			    VAR ___f = FILTERS ( Couts[chantier_id] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[chantier_id] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[chantier_id], ", " )
			    VAR ___x = "Couts[chantier_id] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[cout_id] ), 
			    VAR ___f = FILTERS ( Couts[cout_id] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[cout_id] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[cout_id], ", " )
			    VAR ___x = "Couts[cout_id] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[date] ), 
			    VAR ___f = FILTERS ( Couts[date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[date] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[date], ", " )
			    VAR ___x = "Couts[date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[montant_ht] ), 
			    VAR ___f = FILTERS ( Couts[montant_ht] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[montant_ht] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[montant_ht], ", " )
			    VAR ___x = "Couts[montant_ht] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Couts[type_cout] ), 
			    VAR ___f = FILTERS ( Couts[type_cout] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Couts[type_cout] )
			    VAR ___d = CONCATENATEX ( ___t, Couts[type_cout], ", " )
			    VAR ___x = "Couts[type_cout] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Date] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Date], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Day] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Day], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Month] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Month], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[MonthNo], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Quarter] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Quarter], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[QuarterNo], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Year] ), 
			    VAR ___f = FILTERS ( 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Year], ", " )
			    VAR ___x = "'DateTableTemplate_4bbf770e-f1fa-44d4-914e-86e1438387d1'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Dictionnaire[Colonne] ), 
			    VAR ___f = FILTERS ( Dictionnaire[Colonne] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Dictionnaire[Colonne] )
			    VAR ___d = CONCATENATEX ( ___t, Dictionnaire[Colonne], ", " )
			    VAR ___x = "Dictionnaire[Colonne] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Dictionnaire[Description] ), 
			    VAR ___f = FILTERS ( Dictionnaire[Description] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Dictionnaire[Description] )
			    VAR ___d = CONCATENATEX ( ___t, Dictionnaire[Description], ", " )
			    VAR ___x = "Dictionnaire[Description] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Dictionnaire[Table] ), 
			    VAR ___f = FILTERS ( Dictionnaire[Table] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Dictionnaire[Table] )
			    VAR ___d = CONCATENATEX ( ___t, Dictionnaire[Table], ", " )
			    VAR ___x = "Dictionnaire[Table] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Dictionnaire[Usage principal] ), 
			    VAR ___f = FILTERS ( Dictionnaire[Usage principal] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Dictionnaire[Usage principal] )
			    VAR ___d = CONCATENATEX ( ___t, Dictionnaire[Usage principal], ", " )
			    VAR ___x = "Dictionnaire[Usage principal] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[chantier_id] ), 
			    VAR ___f = FILTERS ( Factures[chantier_id] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[chantier_id] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[chantier_id], ", " )
			    VAR ___x = "Factures[chantier_id] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[date_echeance] ), 
			    VAR ___f = FILTERS ( Factures[date_echeance] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[date_echeance] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[date_echeance], ", " )
			    VAR ___x = "Factures[date_echeance] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[date_facture] ), 
			    VAR ___f = FILTERS ( Factures[date_facture] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[date_facture] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[date_facture], ", " )
			    VAR ___x = "Factures[date_facture] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[date_paiement] ), 
			    VAR ___f = FILTERS ( Factures[date_paiement] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[date_paiement] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[date_paiement], ", " )
			    VAR ___x = "Factures[date_paiement] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[est_impayee_23032026] ), 
			    VAR ___f = FILTERS ( Factures[est_impayee_23032026] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[est_impayee_23032026] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[est_impayee_23032026], ", " )
			    VAR ___x = "Factures[est_impayee_23032026] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[est_retard_23032026] ), 
			    VAR ___f = FILTERS ( Factures[est_retard_23032026] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[est_retard_23032026] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[est_retard_23032026], ", " )
			    VAR ___x = "Factures[est_retard_23032026] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[facture_id] ), 
			    VAR ___f = FILTERS ( Factures[facture_id] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[facture_id] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[facture_id], ", " )
			    VAR ___x = "Factures[facture_id] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[montant_encours_23032026] ), 
			    VAR ___f = FILTERS ( Factures[montant_encours_23032026] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[montant_encours_23032026] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[montant_encours_23032026], ", " )
			    VAR ___x = "Factures[montant_encours_23032026] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[montant_ht] ), 
			    VAR ___f = FILTERS ( Factures[montant_ht] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[montant_ht] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[montant_ht], ", " )
			    VAR ___x = "Factures[montant_ht] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Factures[montant_retard_23032026] ), 
			    VAR ___f = FILTERS ( Factures[montant_retard_23032026] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Factures[montant_retard_23032026] )
			    VAR ___d = CONCATENATEX ( ___t, Factures[montant_retard_23032026], ", " )
			    VAR ___x = "Factures[montant_retard_23032026] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Date], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Day], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Month], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Year], ", " )
			    VAR ___x = "'LocalDateTable_1acbca05-d5f8-4d87-8dee-fb49e24c6070'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Date], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Day], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Month], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Year], ", " )
			    VAR ___x = "'LocalDateTable_27c9e759-045d-4cc0-966e-ebc465906421'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Date], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Day], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Month], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Year], ", " )
			    VAR ___x = "'LocalDateTable_42b3b8e2-a817-4733-a08f-54f5f787af77'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Date], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Day], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Month], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Year], ", " )
			    VAR ___x = "'LocalDateTable_76bd10e6-15fe-4fbd-b33b-623772f629b2'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Date], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Day], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Month], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Year], ", " )
			    VAR ___x = "'LocalDateTable_89fcdb4c-72fa-45a9-8086-5938d970fd8f'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Date], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Day], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Month], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Year], ", " )
			    VAR ___x = "'LocalDateTable_a0d7607d-9abe-4fc1-b8cd-a2c3c5132d5e'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Date], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Day], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Month], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Year], ", " )
			    VAR ___x = "'LocalDateTable_c278d96d-b3fe-4cff-9f15-e7f3e94fbba2'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Date] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Date], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Day] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Day] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Day] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Day], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Day] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Month] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Month], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[MonthNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[MonthNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[MonthNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[MonthNo], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[MonthNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Quarter] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Quarter], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[QuarterNo] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[QuarterNo] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[QuarterNo] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[QuarterNo], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[QuarterNo] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Year] ), 
			    VAR ___f = FILTERS ( 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Year], ", " )
			    VAR ___x = "'LocalDateTable_d4b4c7f7-8c40-4194-b334-2a863aae2be0'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			---- MODEL MEASURES END ----
			
			
			```
		displayFolder: Filtres
		lineageTag: d9f49041-da2d-4287-9774-517ebde9dcd9

	/// Chiffre d'affaire ht
	measure 'CA facture ht' = ```
			SUM(Chantiers[ca_facture_ht]) 
			```
		formatString: 0
		displayFolder: Chiffre d'affaire
		lineageTag: f499c829-177e-4822-bc4b-b0eaf30a5cc4

	measure 'Total Couts HT' =
			
			SUM(Couts[montant_ht])
		formatString: 0
		displayFolder: Couts opérationnels
		lineageTag: 350cf170-ff7f-4b9d-94e7-3d8ffee19cc3

	measure 'CA Prevu HT' = SUM( Chantiers[ca_prevu_ht] )
		formatString: 0
		displayFolder: Chiffre d'affaire
		lineageTag: f40e6bfc-88e0-4973-aca9-48f80b9ca9a1

	measure 'Ecart CA vs Prevu' = [CA facture ht] - [CA Prevu HT]
		formatString: 0
		displayFolder: Chiffre d'affaire
		lineageTag: 57e8160f-caec-4ef7-832d-f132c9485bb3

	measure 'Ecart CA % Prevu' = DIVIDE( [Ecart CA vs Prevu], [CA Prevu HT] )
		displayFolder: Chiffre d'affaire
		lineageTag: 743d5fa1-fbe3-4965-90e8-c54311658936

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nb Chantiers' = COUNTROWS( Chantiers )
		formatString: 0
		displayFolder: Chiffre d'affaire
		lineageTag: c97f53b2-aae5-4d5b-a225-7e67407c73d3

	measure 'CA Moyen / Chantier' = DIVIDE( [CA facture ht], [Nb Chantiers] )
		displayFolder: Chiffre d'affaire
		lineageTag: 31a6e4cd-cdb9-4c10-9964-2786f117e664

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Couts Personnel' =
			
			CALCULATE(
			  SUM( Couts[montant_ht] ),
			  Couts[type_cout] = "Personnel"
			)
		formatString: 0
		displayFolder: Couts opérationnels
		lineageTag: 868edac6-583e-452a-a938-c60b10a32c9f

	measure 'Couts Achats' =
			
			CALCULATE(
			  SUM( Couts[montant_ht] ),
			  Couts[type_cout] = "Achats"
			)
		formatString: 0
		displayFolder: Couts opérationnels
		lineageTag: 3b805dee-5656-4fd3-86a3-df6793373bee

	measure 'Couts Charges Ext.' =
			
			CALCULATE(
			  SUM( Couts[montant_ht] ),
			  Couts[type_cout] = "Charges externes"
			)
		formatString: 0
		displayFolder: Couts opérationnels
		lineageTag: a5b03123-431a-41fc-9e51-8cd02c33c6cb

	measure '% Personnel / CA' =
			
			DIVIDE( [Couts Personnel], [CA facture ht] )
		displayFolder: Couts opérationnels
		lineageTag: 39c70538-ea06-4066-8ea6-23914b7b4b64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultat Net Chantier' =
			
			[CA Facture HT] - [Total Couts HT]
		displayFolder: Rentabilité chantier
		lineageTag: d1fe23fd-a687-40ec-affb-3c87d859aae3

	measure 'Marge Nette %' =
			
			DIVIDE( [Resultat Net Chantier], [CA Facture HT] )
		displayFolder: Rentabilité chantier
		lineageTag: fd7bc459-5c23-414e-b3f8-4d2065914f5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Depassement Budget' =
			
			[Total Couts HT] - [CA Prevu HT]
		displayFolder: Rentabilité chantier
		lineageTag: e351b870-ffc2-40c0-9f36-558be05f273c

	measure 'CA Annuel (EBE)' =
			
			CALCULATE(
			  SUM( Chantiers[ca_facture_ht] ),
			  REMOVEFILTERS( Chantiers[ville] ),
			  REMOVEFILTERS( Chantiers[type_client] ),
			  REMOVEFILTERS( Chantiers[type_travaux] )
			)
		formatString: 0
		displayFolder: EBE annuel
		lineageTag: 89363d4e-df2d-4870-b933-caf6e766fb3f

	measure EBE =
			
			[CA Annuel (EBE)] - [Couts Annuels (EBE)]
		displayFolder: EBE annuel
		lineageTag: 81196c5d-f07a-4f11-8c1c-596e162f37bd

	measure 'Couts Annuels (EBE)' =
			
			CALCULATE(
			  SUM( Couts[montant_ht] ),
			  REMOVEFILTERS( Chantiers[ville] ),
			  REMOVEFILTERS( Chantiers[type_client] ),
			  REMOVEFILTERS( Chantiers[type_travaux] )
			)
		formatString: 0
		displayFolder: EBE annuel
		lineageTag: 92bdee4c-085d-49c8-a75b-b524cdbdf408

	measure 'Taux EBE %' =
			
			DIVIDE( [EBE], [CA Annuel (EBE)] )
		displayFolder: EBE annuel
		lineageTag: 48c7764a-4436-42c6-b6f1-7768ddc1ff00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBE Annee Prec.' =
			
			CALCULATE(
			  [EBE],
			  PREVIOUSYEAR( 'Calendrier'[Date] )
			)
		formatString: 0
		displayFolder: EBE annuel
		lineageTag: 858ee5d4-b23c-49da-980f-6cc79e140e24

	measure 'Variation EBE vs N-1' =
			
			DIVIDE(
			  [EBE] - [EBE Annee Prec.],
			  [EBE Annee Prec.]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: EBE annuel
		lineageTag: 0787502f-1ddc-4c1f-abec-609cd5dccdda

	measure 'Montant Facture' =
			
			SUM( Factures[montant_ht] )
		formatString: 0
		displayFolder: Trésorerie & Encaissements
		lineageTag: 1b0a13f2-1970-4de6-8a92-75bbf13b9f13

	measure 'Montant Encaisse' =
			
			CALCULATE(
			  SUM( Factures[montant_ht] ),
			  Factures[date_paiement] <> BLANK()
			)
		formatString: 0
		displayFolder: Trésorerie & Encaissements
		lineageTag: b7535766-6ea4-4a0e-9ced-cecdf0ea6f03

	measure 'Ecart Facture-Encaisse' =
			
			[Montant Facture] - [Montant Encaisse]
		formatString: 0
		displayFolder: Trésorerie & Encaissements
		lineageTag: fc79c7ab-0d43-421c-8e4f-cd5aa9ec32a6

	measure 'Delai Moyen Paiement' =
			
			AVERAGEX(
			  FILTER(
			    Factures,
			    Factures[date_paiement] <> BLANK()
			  ),
			  Factures[date_paiement] - Factures[date_echeance]
			)
		displayFolder: Trésorerie & Encaissements
		lineageTag: 999ce824-82c5-4b88-b82b-54d4f7a2e214

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Montant En Retard' =
			
			CALCULATE(
			  SUM( Factures[montant_retard_23032026] ),
			  REMOVEFILTERS()
			)
		formatString: 0
		displayFolder: Relances & Retards
		lineageTag: f26d2f95-11c9-4883-b299-073d8319c7e0

	measure 'Nb Factures En Retard' =
			
			CALCULATE(
			  COUNTROWS( Factures ),
			  Factures[est_retard_23032026] = 1,
			  REMOVEFILTERS()
			)
		formatString: 0
		displayFolder: Relances & Retards
		lineageTag: ca2bfd18-7fdf-4148-b876-6cb04025e9f8

	measure 'Jours de Retard' =
			
			DATEDIFF(
			  MAX( Factures[date_echeance] ),
			  TODAY(),
			  DAY
			)
		formatString: 0
		displayFolder: Relances & Retards
		lineageTag: cfbeb973-a43a-4352-9468-191fb1f49336

	measure '% CA En Souffrance' =
			
			DIVIDE(
			  [Montant En Retard],
			  CALCULATE( [CA Facture HT], REMOVEFILTERS() )
			)
		displayFolder: Relances & Retards
		lineageTag: b567efc0-352d-48a6-9703-9098ec3cde97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FORMAT montant + nb factures en retards' = ```
			
			FORMAT([Montant En Retard], "# ##0 €") 
			& " · " & 
			FORMAT([Nb Factures En Retard], "0") & " fact."
			```
		displayFolder: Relances & Retards
		lineageTag: 3fd0a309-55c7-4734-8a10-1323cfad549d

	measure 'FORMAT montant + nb factures en retards (long)' = ```
			
			FORMAT([Nb Factures En Retard], "0") & " factures en retard" 
			& " · " & 
			FORMAT([Montant En Retard], "# ##0 €") & " non encaissés" 
			```
		displayFolder: Relances & Retards
		lineageTag: 13385072-e1bf-4e25-9f86-78bb03b7e3c3

	measure 'Valeur EBE Waterfall' =
			
			VAR etape = SELECTEDVALUE('Structure EBE'[Etape])
			VAR ebe = [CA facture ht] - [Couts Achats] - [Couts Charges Ext.] - [Couts Personnel]
			RETURN
			SWITCH(etape,
			    "CA",               [CA facture ht],
			    "Achats",           -[Couts Achats],
			    "Charges externes", -[Couts Charges Ext.],
			    "Personnel",        -[Couts Personnel],
			    "EBE",              BLANK()
			)
		formatString: 0
		displayFolder: EBE annuel
		lineageTag: 5fecfc79-225c-4538-a200-d69f87f443f1

	measure 'FORMAT Part EBE' =
			
			VAR _pct = ROUND([Taux EBE %] * 100, 1)
			RETURN
			IF(
			    ABS(_pct - ROUND(_pct, 0)) < 0.000001,
			    FORMAT(_pct, "0"),
			    FORMAT(_pct, "0.0")
			) & " % du CA"
		displayFolder: EBE annuel
		lineageTag: 2bcf6ec4-ed80-4d98-8072-1f8c9e9e0343

	measure 'Différence CA prévu et CA facturé' = [CA facture ht] - [CA Prevu HT]
		formatString: 0
		displayFolder: Chiffre d'affaire
		lineageTag: 4723ff7f-30c7-4a49-b49a-d2ba5c9e4de9

	measure 'Encaissements Manqués Cumulés' =
			
			CALCULATE(
			    SUM( Factures[montant_retard_23032026] ),
			    FILTER(
			        ALL( 'Calendrier' ),
			        'Calendrier'[Date] <= MAX( 'Calendrier'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Trésorerie & Encaissements
		lineageTag: 371a9102-ffa0-4e8b-b1ed-95c4ba0b0675

	measure 'Action à mener' =
			
			IF(
			    MAX( Factures[est_retard_23032026] ) <> 1,
			    BLANK(),
			    SWITCH(
			        TRUE(),
			        MAX( Factures[JoursRetard] ) < 30, "Rappel amiable",
			        MAX( Factures[JoursRetard] ) < 60, "Relance formelle",
			        MAX( Factures[JoursRetard] ) < 90, "Mise en demeure",
			        "Contentieux"
			    )
			)
		displayFolder: Relances & Retards
		lineageTag: ede49c5d-4906-4b65-a4d8-50572fce24c4

	measure 'Niveau Urgence' =
			
			SWITCH(
			    TRUE(),
			    MAX( Factures[JoursRetard] ) < 30, 1,
			    MAX( Factures[JoursRetard] ) < 60, 2,
			    MAX( Factures[JoursRetard] ) < 90, 3,
			    4
			)
		formatString: 0
		displayFolder: Relances & Retards
		lineageTag: b97eb127-08f3-4de2-98eb-569528c8e428

	column Value
		isHidden
		formatString: 0
		lineageTag: 0967da8d-e855-4966-b9df-c4abd29e8b02
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Mesures = calculated
		mode: import
		source = Row("Value", BLANK())

	annotation PBI_Id = b30450085a2749dfa553103aac4e23f9

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

